FETCH_P = 'P'
FETCH_V = 'V'

CELSIUS_LABEL = '摄氏度'
DENSITY_LABEL = '密度'
VOLUME_LABEL = '体积'
ATMOSPHERIC_LABEL = '大气压强'
GRAVITY_LABEL = '重力加速度'
AREA_LABEL = '管道横截面积'
OPERATOR_LABEL = '操作人员'
DATE_LABEL = '日期'
MEASURE_RESULT = '测量结果'

WAITING = '未开始'
CALCULATING = '计算中'

# 计算参数
DEFAULT_ATOMSPHERIC = 1.013 * 10e5
DEFAULT_GRAVITY = 0.98
DEFAULT_DENSITY = 1

